services:
  local_sftp:
    image: atmoz/sftp:alpine
    command: "user:password:::/tmp/files"
    container_name: local_sftp
    ports:
      - "22:22"
    volumes:
      - ./ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key